### ISSUE TITLE
老师为什么会这样啊😢

### ISSUE THREAD

**Issue by YUSHI666** [rksys/cs2017_queue#4]
<img width="624" alt="2018-05-23 14 48 30" src="https://user-images.githubusercontent.com/39413268/40403916-4c4c7a98-5e98-11e8-9a19-41aefff0eff6.png">
[Untitled-1.pdf](https://github.com/rksys/cs2017_queue/files/2029562/Untitled-1.pdf)

**Comment by rksys** [comment]
你的完整代码贴出来i？

**Comment by YUSHI666** [comment]
#include<stdio.h>
#include<stdlib.h>
#include<string.h>
typedef struct node{
    int val;
    struct node* prev;
    struct node* next;
}Node;
typedef struct{
    Node* head;
    Node* tail;
}Queue;
void Queue_print(Queue* q){
    Node* cur=q->head->next;
    while(cur!=q->tail){
        printf("%d->",cur);
        cur=cur->next;
    }
    printf("NULL\n");
}
Queue_create(){
    Queue* q=(Queue*) malloc(sizeof(Queue));
    q->head=(Node*) malloc(sizeof(Node));
    q->tail=(Node*) malloc(sizeof(Node));
    q->head->next=q->tail;
    q->tail->prev=q->head;
    head->val=0;
    tail->val=0;
    head->prev=NULL;
    tail->next=NULL;
    return q;
}
void Queue_append(Queue* q,int val){
    Queue* New_node=(Queue*)malloc(sizeof(Queue));
    New_node->val=val;
    Node* Original=q->tail->prev;
    Original->next=New_node;
    q->tail->prev=New_node;
    New_node->prev=Original;
    New_node->next=q->tail;
}
int Queue_pop(Queue*q){
    Node* ret=q->head->next;
    int ret_val=ret->val;
    q->head->next=ret->next;
    Node* New_head_next=ret->next;
    New_head_next->prev=q->head;
    free(ret);
    return(ret_value);
}
void Queue_delete(Queue* q,int target){
    Queue* cur=q->head->next;
    while(cur!=q->tail&&cur->val!=target){
        cur=cur->next;
    }
    if(cur!=q->tail){
        Node* Original_cur_next=ret->next;
        Node* Original_cur_prev=ret->prev;
        Original_cur_next->prev=Original_ret_prev;
        Original_cur_prev->next=Original_ret_next;
        free(cur);
} }
int Queue_insert_somewhere(Queue* q,int val,int ins_val){
    int success= 0;
    Node* cur=q->head->next;
    while(cur!=q->tail&&cur->val!=val){
        cur=cur->next;
    }
    if(cur!=q->tail){
        Node* New_node=(Node*)malloc(sizeof(Node));
        Node* New_node_next=cur->next;
        New_node->val=ins_val;
        New_node->next=New_node_next;
        New_node->prev=cur;
        cur->next=New_node_next;
        New_node_next->prev=New_node;
    }
    else success= 1;
    return success;
}
void readfile(Queue* q, char* filename){
    File* fp=fopen("filename","r");
    if(fp==NULL){
        printf("file open on %s error!",filename);
    }
    int elem;
    while(!feof(fp)){
        scanf(fp,"%d",&elem);
        Queue_append(q,elem);
    }
    fclose(fp);
}
void interaction(){
    char* command[100];
    Queue* queue=Queue_create();
    while(scanf("%s",command){
        if(strcmp("command","print")==0){

Queue_print(queue);
        }else if(strcmp("command","append")==0){
            scanf("%d",&elem);
            Queue_create(queue,elem);
            printf("appened val %d\n",elem);
        }else if(strcmp("command","pop")==0){
            int val=Queue_pop(queue);
            printf("popped val %d\n",val);
        }else if("command","delete"==0){
            int target;
            scanf("%d",&target);
            Queue_delete(queue,target);
            printf("deleted val %d\n",)
        }else if(strcmp("command","readfile")==0){
            char fn[100];
            scanf("%s",fn);
            File* fp=fopen("fn","r");
            if(!fp){
                printf("No such file\n");
            }else{
                readfile(queue,fn);
               printf("Gonna read file %s\n",fn);
} }else{
            printf("No such command\n");
            fflush(stdout);
            strcpy(command,"");
} }
}
int main(int argc,char* argv[]){
    Queue_interaction();
    return 0;
}

**Comment by YUSHI666** [comment]
其实我图片下面那个网址也是我的程序
